package com.gamefactory.core.llm

/**
 * Deterministic offline provider. Used for unit tests and for the app's
 * "Demo mode" so the whole pipeline can be exercised without any API key.
 */
class MockLlmClient(
    override val name: String = "mock",
    override val supportedCapabilities: Set<LlmCapability> = setOf(
        LlmCapability.PLANNING, LlmCapability.CODING, LlmCapability.QA,
        LlmCapability.SECURITY, LlmCapability.LISTING
    ),
    /** If > 0, the first N calls throw (to test router fallback). */
    var failFirstNCalls: Int = 0
) : LlmClient {

    private var calls = 0
    val callsMade: Int get() = calls

    override fun complete(request: LlmRequest): String {
        if (failFirstNCalls > 0) {
            failFirstNCalls--
            throw LlmException(name, "injected failure for testing")
        }
        calls++
        return when (request.capability) {
            LlmCapability.PLANNING -> plan(request.userPrompt)
            LlmCapability.CODING -> code(request.userPrompt)
            LlmCapability.QA, LlmCapability.SECURITY -> review(request.userPrompt)
            LlmCapability.LISTING -> listing(request.userPrompt)
        }
    }

    private fun topic(prompt: String): String {
        val words = prompt.lowercase().filter { it.isLetter() || it == ' ' }.split(' ').filter { it.length > 3 }
        return (words.firstOrNull { it !in listOf("build", "create", "make", "game", "app", "with", "that", "this") }
            ?: "factory") .replaceFirstChar { it.uppercase() }
    }

    private fun plan(prompt: String): String {
        val topic = topic(prompt)
        return """
            TASK core.window | deps:  | Set up main window, project settings and entry scene
            TASK player.movement | deps: core.window | Implement responsive player movement and collision
            TASK player.input | deps: player.movement | Map touch and keyboard input to player actions
            TASK gameplay.loop | deps: player.input | Implement core gameplay loop and win/lose states
            TASK ui.hud | deps: core.window | Build HUD showing score, health and progress
            TASK ui.menu | deps: ui.hud | Main menu, pause menu and settings screen
            TASK world.levels | deps: player.movement | Design and build $topic levels with progression
            TASK assets.sprites | deps: world.levels | Generate/collect sprite and tile assets
            TASK audio.sfx | deps: core.window | Add sound effects and background music hooks
            TASK testing.regression | deps: gameplay.loop, ui.menu | Regression test suite for core flows
            TASK security.audit | deps: gameplay.loop | Scan code for secrets and unsafe patterns
            TASK listing.metadata | deps: ui.menu | Store listing title, description and keywords
        """.trimIndent()
    }

    private fun code(prompt: String): String {
        val taskId = prompt.lineSequence().firstOrNull { it.startsWith("TASK_ID:") }?.removePrefix("TASK_ID:")?.trim()
            ?: "unknown.task"
        val fileName = taskId.replace('.', '_') + ".gd"
        val body = """
            extends Node
            # Auto-generated by Game Factory (mock provider) for task: $taskId

            var _ready := false

            func _ready() -> void:
                _ready = true
                print("$taskId initialized")

            func _process(delta: float) -> void:
                if not _ready:
                    return
                # TODO: implement $taskId behaviour
                pass
        """.trimIndent()
        return "FILE $fileName\n---\n$body\nENDFILE\n"
    }

    private fun review(prompt: String): String = "PASS no issues found"

    private fun listing(prompt: String): String {
        val t = topic(prompt)
        return "TITLE: $t Factory Game\nDESC: An offline-first game built by the Game Factory pipeline.\nKEYWORDS: arcade, offline, factory"
    }
}
